$hypr = ~/.config/hypr
$hl = $hypr/hyprland
$cConf = ~/.config/caelestia

# Variables (colours + other vars)
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec = cp -L --no-preserve=mode --update=none $hypr/scheme/default.conf $hypr/scheme/current.conf
source = $hypr/scheme/current.conf
source = $hypr/variables.conf

# User variables
exec = mkdir -p $cConf && touch -a $cConf/hypr-vars.conf
source = $cConf/hypr-vars.conf

# Default monitor conf
monitor = DP-1, 2560x1440@180, auto, 1
monitor = HDMI-A-1, 1920x1080@60, 1080x0, 1, transform,3

source = $hl/env.conf
source = $hl/general.conf
source = $hl/input.conf
source = $hl/misc.conf
source = $hl/animations.conf
source = $hl/decoration.conf
source = $hl/group.conf
source = $hl/execs.conf
source = $hl/rules.conf
source = $hl/gestures.conf
source = $hl/keybinds.conf

# User configs
exec = mkdir -p $cConf && touch -a $cConf/hypr-user.conf
source = $cConf/hypr-user.conf


input {
    kb_layout = tr
    kb_variant = ,qwerty
}

plugin:dynamic-cursors {
    enabled = true

    # tilt | rotate | stretch | none
    mode = stretch

    threshold = 2

    rotate {
        length = 20
        offset = 0.0
    }

    tilt {
        limit = 5000
        function = negative_quadratic  # linear | quadratic | negative_quadratic
        window = 100
        full_tilt = 60
    }

    stretch {
        limit = 5400
        function = quadratic
        window = 90
    }

    shake {
        enabled = false
        threshold = 6.0
        base = 4.0        # magnification level when shake starts
        speed = 4.0       # magnification increase per second
        timeout = 2000    # ms to stay magnified after shake ends
        nearest = true
        effects = false
    }
}
