# ### Hyprland ###
# Apps
$streaming = com.obsproject.Studio
$terminal = kitty
$editor = zeditor
$github = github-desktop
$fileExplorer = thunar
$spotify = com.spotify.Client
$control = pavucontrol
$primaryBrowser = firefox
$secondaryBrowser = com.vivaldi.Vivaldi

# Touchpad
$touchpadDisableTyping = true
$touchpadScrollFactor = 0.3
$workspaceSwipeFingers = 4
$gestureFingers = 3
$gestureFingersMore = 4

# Blur
$blurEnabled = true
$blurSpecialWs = false
$blurPopups = true
$blurInputMethods = true
$blurSize = 8
$blurPasses = 2
$blurXray = false

# Shadow
$shadowEnabled = true
$shadowRange = 20
$shadowRenderPower = 3
$shadowColour = rgba($surfaced4)

# Gaps
$workspaceGaps = 20
$windowGapsIn = 10
$windowGapsOut = 40
$singleWindowGapsOut = 20

# Window styling
$windowOpacity = 0.95
$windowRounding = 10

$windowBorderSize = 3
$activeWindowBorderColour = rgba($primarye6)
$inactiveWindowBorderColour = rgba($onSurfaceVariant11)

# Misc
$volumeStep = 9  # In percent
$cursorTheme = 0
$cursorSize = 24


# ### Keybinds ###
# Workspaces


$kbMoveWinToWs = Super+Alt
$kbMoveWinToWsGroup = Ctrl+Super+Alt
$kbGoToWs = Super
$kbGoToWsGroup = Ctrl+Super

$kbNextWs = Ctrl+Super, right
$kbPrevWs = Ctrl+Super, left

$kbToggleSpecialWs = Super, S

# Window groups
$kbWindowGroupCycleNext = Alt, Tab
$kbWindowGroupCyclePrev = Shift+Alt, Tab
$kbUngroup = Super, U
$kbToggleGroup = Super, Comma

# Window actions
$kbMoveWindow = Super, Z
$kbResizeWindow = Super, X
$kbWindowPip = Super+Alt, Backslash
$kbPinWindow = Super, P
$kbWindowFullscreen = Super, F
$kbWindowBorderedFullscreen = Super+Alt, F
$kbToggleWindowFloating = Super, Space
$kbCloseWindow = Super, X
$kbWindowMaximize = Super, D

# Special workspace toggles
$kbSpecialWsSys = Super, C
$kbSpecialWsMusic = Super, S
$kbSpecialWsCommunication = Super, C
$kbSpecialWsTodo = Super, R
$kbSpecialWsFile = Super, F
$kbSpecialWsGame = Super, A
$kbSpecialWsTerminal = Super, W
$kbSpecialWsStream = Super, G
$kbSpecialWsDesign = Super, Y

# Apps
$kbAppTerminal = Super, T
$kbAppEditor = Super, B
$kbAppGithub = Super, G
$kbAppExplorer = Super, E
$kbAppSpotify = Super, W
$kbAppControl = Super, N
$kbAppPrimaryBrowser = Super, Q
$kbAppSecondaryBrowser = Super+Alt, Q
$kbAppStream = Super+Alt, G

# Misc
$kbSession = Ctrl+Alt, Delete
$kbClearNotifs = Ctrl+Alt, C
$kbShowPanels = Super, K
$kbLock = Super, L
$kbRestoreLock = Super+Alt, L
