// brain-hubs.mjs - regenerate the vault's generated hub notes from the folders. Idempotent.
// Plan: C:\obsidian\root\40-Plans\2026-09-20-vault-governance-overhaul\stages\vault-governance-03-folder-restructure.md
//
// Hubs exist so every note stays reachable from 00-MOC-Root in two hops (records in three: a
// daily note or a commit note is reached through its generated index). They are written from the
// folder contents every time, so they cannot drift - never edit one by hand.
import { readdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, basename } from "node:path";
import { VAULT } from "./brain-lib.mjs";

const today = new Date().toISOString().slice(0, 10);
const fm = (tags) => ["---", "type: moc", "project: knowledge", `tags: [moc, ${tags}, generated]`, "created: 2026-09-21", `updated: ${today}`, "status: active", "---", ""];
const md = (dir) => (existsSync(dir) ? readdirSync(dir).filter((f) => f.endsWith(".md") && !f.startsWith("00-MOC")) : []);
const title = (p) => (/^# (.+)$/m.exec(readFileSync(p, "utf8"))?.[1] ?? basename(p, ".md")).replace(/[|\]]/g, "-");

function sessions() {
  const root = join(VAULT, "30-Sessions");
  const out = [...fm("sessions"), "# Sessions", "", "Daily logs, 05:00 TST rollover. Generated by `brain-hubs`."];
  for (const y of readdirSync(root).filter((d) => /^\d{4}$/.test(d)).sort().reverse())
    for (const m of readdirSync(join(root, y)).filter((d) => /^\d{2}$/.test(d)).sort().reverse()) {
      const days = md(join(root, y, m)).sort().reverse();
      if (days.length) out.push("", `## ${y}-${m}`, "", ...days.map((f) => `- [[${f.slice(0, -3)}]]`));
    }
  writeFileSync(join(root, "00-MOC-Sessions.md"), `${out.join("\n")}\n`, "utf8");
}

function plans() {
  const root = join(VAULT, "40-Plans");
  const out = [...fm("plans"), "# Plans", "", "Cross-repo plans, one folder each: `<slug>/<slug>.md` is the plan. Generated by `brain-hubs`."];
  for (const d of readdirSync(root, { withFileTypes: true }).filter((e) => e.isDirectory()).map((e) => e.name).sort().reverse()) {
    const main = join(root, d, `${d}.md`);
    if (!existsSync(main)) continue;
    const status = /^status:\s*(\S+)/m.exec(readFileSync(main, "utf8"))?.[1] ?? "?";
    out.push("", `## ${title(main)}`, "", `- [[${d}]] — \`${status}\``);
    for (const f of md(join(root, d)).filter((f) => f !== `${d}.md`).sort()) out.push(`- [[${f.slice(0, -3)}]]`);
    for (const sub of ["stages", "evidence"]) for (const f of md(join(root, d, sub)).sort()) out.push(`  - ${sub}: [[${f.slice(0, -3)}]]`);
  }
  writeFileSync(join(root, "00-MOC-Plans.md"), `${out.join("\n")}\n`, "utf8");
}

function ops() {
  const root = join(VAULT, "50-Ops");
  const out = [...fm("ops"), "# Ops", "", "Machine-written operational records. Generated by `brain-hubs`."];
  for (const [sub, label] of [["Commits", "Commits — one note per commit, indexed by month"], ["Usage", "Usage — tokens, models, cost"], ["Health", "Health — the daily vault sweep"]]) {
    const files = md(join(root, sub)).sort().reverse();
    if (files.length) out.push("", `## ${label}`, "", ...files.map((f) => `- [[${f.slice(0, -3)}]]`));
  }
  const loose = md(root);
  if (loose.length) out.push("", "## Other", "", ...loose.map((f) => `- [[${f.slice(0, -3)}]]`));
  writeFileSync(join(root, "00-MOC-Ops.md"), `${out.join("\n")}\n`, "utf8");
}

try { sessions(); plans(); ops(); } catch (e) { process.stderr.write(`brain-hubs: ${e?.message ?? e}\n`); process.exitCode = 1; }
