# ~/.config/kitty/kitty.conf

# --- GÖRÜNÜM VE FONT ---
font_family      JetBrainsMono Nerd Font
font_size        20.0
# Görseldeki ferahlık için kenar boşluğu
window_padding_width 15 
# Caelestia arkaplanı yönetecek ama varsayılan olarak tam opak olsun:
background_opacity 1.0
allow_remote_control yes

# --- CURSOR (İMLEÇ VE İZİ) ---
cursor_shape     block
# İmleç izini (Cursor Trail) açan ayarlar:
cursor_trail 3
cursor_trail_decay 0.1 0.3
cursor_trail_start_threshold 2

# --- RENKLER ---
# Renk ayarlarını sildik, çünkü fish config dosyasındaki
# 'cat sequences.txt' komutu bunları otomatik yükleyecek.

shell /usr/bin/fish
editor .
