[FileDialog]
history=file:///run/media/atlasata/ATLAS SSD/ATLASATA - BACKUPS.1/LATEST - BCK.9/obs/scenes/Caelestia, file:///home/atlasata/stream, file:///home/atlasata/stream/files/caelestia/jpg, file:///home/atlasata/stream/files/caelestia/mp4, file:///home/atlasata/stream/files/caelestia/webm, file:///home/atlasata/stream/files/caelestia/widgets/html
lastVisited=file:///home/atlasata/stream/files/caelestia/widgets/html
qtVersion=6.11.1
shortcuts=file:///home/atlasata, file:///home/atlasata/Downloads, file:mods
sidebarWidth=108
treeViewHeader="@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\x1\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x2\x44\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\x1,\0\0\0\x1\0\0\0\0\0\0\0K\0\0\0\x1\0\0\0\0\0\0\0K\0\0\0\x1\0\0\0\0\0\0\0\x82\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1)"
viewMode=Detail
